name: Deploy App to Azure App Service

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build with Maven
        run: mvn clean install -DskipTests
      - name: Upload Artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: mype-navigator-artifact
          path: ${{ github.workspace }}/target/*.jar
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Artifact for deployment job
        uses: actions/download-artifact@v2
        with:
          name: mype-navigator-artifact
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: mype-nagivator-api
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: '*.jar'
